name: terraform plan

on:
  pull_request:
    branches: [ "main" ]
    types: [opened, synchronize, reopened]
  workflow_dispatch:

env:
  aws_default_region: ap-northeast-1
  tf_version: 1.10.4
  deploy_env: ${{ github.event.inputs.environment || 'dev' }}
  ACTIONS_RUNNER_DEBUG: true
  ACTIONS_STEP_DEBUG: true

permissions:
  id-token: write
  contents: read
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment || 'dev' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@ececac1a45f3b08a01d2dd070d28d111c5fe6722 # v4
        with:
          aws-region: ${{ env.aws_default_region }}
          role-to-assume: ${{ secrets.AWS_GITHUB_ACTIONS_OIDC_ROLE_ARN }}
          role-chaining: true

      - name: apt install unzip
        run: |
          sudo apt update
          sudo apt install unzip

      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: "18"

      - name: Check terraform
        uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3
        with:
          terraform_version: ${{ env.tf_version }}

      - name: Terraform fmt
        id: fmt
        run: |
          terraform -chdir=infra/terraform fmt -check -recursive

      # plan (backend)
      - name: Terraform plan (backend)
        id: plan_backend
        run: |
          terraform -chdir=infra/terraform/environment/${{ env.deploy_env }}/backend init
          terraform -chdir=infra/terraform/environment/${{ env.deploy_env }}/backend plan

      # plan (CICD)
      - name: Terraform plan (CICD)
        id: plan_cicd
        run: |
          terraform -chdir=infra/terraform/environment/${{ env.deploy_env }}/cicd init
          terraform -chdir=infra/terraform/environment/${{ env.deploy_env }}/cicd plan

      # plan (AWS)
      - name: Terraform plan (AWS)
        id: plan_aws
        run: |
          terraform -chdir=infra/terraform/environment/${{ env.deploy_env }}/aws init
          terraform -chdir=infra/terraform/environment/${{ env.deploy_env }}/aws plan
