name: terraform apply

on:
  workflow_dispatch:

env:
  aws_default_region: "ap-northeast-1"
  tf_version: 1.10.4
  deploy_env: ${{ github.event.inputs.environment || 'dev' }}
  ACTIONS_RUNNER_DEBUG: true
  ACTIONS_STEP_DEBUG: true

permissions:
  id-token: write
  pull-requests: write
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  terraform-apply:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment || 'dev' }}
    if: ${{ github.ref_name == 'main' || github.event.inputs.environment == 'dev' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@4fc4975a852c8cd99761e2de1f4ba73402e44dd9 # v4
        with:
          aws-region: ${{ env.aws_default_region }}
          role-to-assume: ${{ secrets.AWS_GITHUB_ACTIONS_OIDC_ROLE_ARN }}
          role-chaining: true

      - name: apt install unzip
        run: |
          sudo apt update
          sudo apt install unzip

      - name: apt install zip
        run: |
          sudo apt update
          sudo apt install zip

      - name: apt install maven
        run: |
          sudo apt update
          sudo apt install maven

      - uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4
        with:
          node-version: "18"

      - name: Setup-terraform
        uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3
        with:
          terraform_version: ${{ env.tf_version }}

      # apply (backend)
      - name: terraform apply backend
        run: |
          terraform -chdir=infra/terraform/environment/${{ env.deploy_env }}/backend init
          terraform -chdir=infra/terraform/environment/${{ env.deploy_env }}/backend apply -auto-approve
      
      # apply (CICD)
      - name: Terraform apply CICD
        run: |
          terraform -chdir=infra/terraform/environment/${{ env.deploy_env }}/cicd init
          terraform -chdir=infra/terraform/environment/${{ env.deploy_env }}/cicd apply -auto-approve
      
      # apply (AWS)
      - name: Terraform apply AWS
        id: apply_aws
        run: |
          terraform -chdir=infra/terraform/environment/${{ env.deploy_env }}/aws init
          terraform -chdir=infra/terraform/environment/${{ env.deploy_env }}/aws apply -auto-approve