name: TFLint

on:
  pull_request:
    branches: [ "main" ]
    types: [opened, synchronize, reopened]
  workflow_dispatch:

env:
  tflint_version: v0.54.0

permissions:
  id-token: write
  contents: read
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tflint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v4
      name: Checkout source code

    - uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4
      name: Cache plugin dir
      with:
        path: ~/.tflint.d/plugins
        key: ubuntu-latest-tflint-${{ hashFiles('.tflint.hcl') }}

    - uses: terraform-linters/setup-tflint@4cb9feea73331a35b422df102992a03a44a3bb33 # v4
      name: Setup TFLint
      with:
        tflint_version:  ${{ env.tflint_version }}

    - name: Init TFLint
      run: tflint --init

    - name: Run TFLint against modules
      run: |
        #!/usr/bin/env bash

        ROOT_DIR=$GITHUB_WORKSPACE
        TFLINT_CONFIG_FILE="$ROOT_DIR/.tflint.hcl"
        MODULES_DIR="$ROOT_DIR/infra/terragrunt/modules"

        for module_dir in $(find "$MODULES_DIR" -maxdepth 5 -type d); do
          echo "Running tflint at: $module_dir"
          pushd "$module_dir" >/dev/null
            TFLINT_CONFIG_FILE="$TFLINT_CONFIG_FILE" tflint --recursive
          popd >/dev/null
        done

