name: tfsec

on:
  pull_request:
    branches: [ "main" ]
    types: [opened, synchronize, reopened]
  workflow_dispatch:

env:
  tfsec_version: v1.28.14

permissions:
  id-token: write
  contents: read
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tfsec:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      name: Checkout source code

    - name: Install tfsec
      run: |
        TFSEC_VERSION=${{ env.tfsec_version }}
        INSTALL_SCRIPT_URL="https://raw.githubusercontent.com/aquasecurity/tfsec/${TFSEC_VERSION}/scripts/install_linux.sh"
        curl -sSL "$INSTALL_SCRIPT_URL" -o install_tfsec.sh
        chmod +x install_tfsec.sh
        TFSEC_VERSION=${{ env.tfsec_version }} TFSEC_INSTALL_PATH=/usr/local/bin ./install_tfsec.sh

    - name: Run tfsec against modules
      run: |
        ROOT_DIR=$GITHUB_WORKSPACE
        MODULES_DIR="$ROOT_DIR/infra/terragrunt/modules"

        for module_dir in $(find "$MODULES_DIR" -maxdepth 5 -type d); do
          echo "Running tfsec at: $module_dir"
          tfsec "$module_dir"
        done
